#!/bin/bash

function setup() {
	docker build . -t crypto-exchange
	# docker run -d -p 8080:80 --name exchange crypto-exchange
	# docker run -d -p 8080:443 --name exchange crypto-exchange
	docker run -d -p 80:80 -p 443:443 --name exchange crypto-exchange
	docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
}
function start() {
	docker start exchange
}
function stop() {
	docker stop exchange
}
function remove() {
	docker rm exchange -f
}
function clean() {
	remove
	docker rmi crypto-exchange
}

function setup_combined() {
	# docker run -it -p 49160:8080 -d -v //d/localhost/htdocs/test/tmp/react-crypto-prices:/usr/src/app --name exchange-tmp node:13.8.0
	docker run -it -p 49160:8080 -d -v "$PWD":/usr/src/app --name exchange-tmp node:13.8.0
	docker exec -w /usr/src/app exchange-tmp npm install
	docker exec -w /usr/src/app exchange-tmp npm run build
	rm -rf ../exchange
	mkdir ../exchange
	cp -r build/* ../exchange
	rm -rf node_modules build
	docker rm -f exchange-tmp
}

$1 $2 $3